### ISSUE TITLE
In dev mode google ads are added on each reload

### ISSUE THREAD

**Issue by GingerFitzgerald** [iebb/F1ManagerSaveReader#1]
## Description
When running the application by npm run dev the google ads add task seems to be executed on each refresh of the page. 

## To Reproduce

1. run the app in dev mode locally and connect to localhost:3000 
2. open the web console
3. click the reload button of your browser
4. Now an error pops up stating `TagError: adsbygoogle.push() error: All ins elements in the DOM with class=adsbygoogle already have ads in them.`
**
![image](https://github.com/iebb/F1ManagerSaveReader/assets/9789548/637d03a8-629b-41c8-b311-bda77048ce15)
**

## Notes
this is seems to only affect dev mode

**Comment by iebb** [comment]
I've removed the ads block :D
