### ISSUE TITLE
Created team doesn't display under car parts.

### ISSUE THREAD

**Issue by brooksey8184** [iebb/F1ManagerSaveReader#10]
Using a save from F1 Manager 2024.

Navigate to Parts > Car Parts > All other sub menus (Powertrains, Chassis, Front Wing, Rear Wing, Sidepods, Underfloor, Suspension, ERS and Gearbox)

Created team isn't present for the user to modify values if they wish. I know it's day it's day 1 so this maybe something you are already look at just wanted to post a message. Thanks for the webtool it's really amazing and easy to use.

**Comment by iebb** [comment]
Does it work now?

**Comment by brooksey8184** [comment]
@iebb - Tested today and they do appear now. Good to close.
