### ISSUE TITLE
--RESOLVED-- Facilities Tab returns 404: Not_Found

### ISSUE THREAD

**Issue by brooksey8184** [iebb/F1ManagerSaveReader#11]
07/27/24 - Issue appears to be resolved. Clicked facility tab and it load, tested up and down button and refresh button on following tab (Car Development, Staff and Operations) and all are working as expected.

Thanks
- Brooksey

Repro Steps:
1. Upload F1 Manager 2024 save.
2. Navigate to Facilities tab
3. Notice 404 Not_Found page
![404 Error](https://github.com/user-attachments/assets/b301460a-2df6-4493-a9aa-d769944c83d9)

Thanks for all the hard work!

**Comment by iebb** [comment]
I have migrated the whole system from Vercel to Cloudflare, removing all server rendering, in order to have an offline version.

This should be a temporary thing.
