### ISSUE TITLE
Staff Other than Drivers Contract Length are showing 'NaN'

### ISSUE THREAD

**Issue by CalianaLynx** [iebb/F1ManagerSaveReader#19]
Staffs other than drivers contract length are not showing the years, instead it shows NaN.
Tried clicking +1 but i don't think its working (cmiiw)

Go to People tab,
Technical Chief, Race Engineer, Sporting Director and Head of Aero are all showing NaN in their contract length.

**Expected behavior**
All Staffs contract length should show the year, not NaN

**Screenshots**
Attached the screenshot
![NaN Bug Report](https://github.com/user-attachments/assets/500e2b0c-5643-42d4-aa72-b453cf5ba8ca)

Thank you for your help :)

**Comment by iebb** [comment]
Contracts in 24 are working a bit differently, and yes I'm working to resolve the issue
