### ISSUE TITLE
Do not display the hint that there is a desktop app when accessed using the app

### ISSUE THREAD

**Issue by GingerFitzgerald** [iebb/F1ManagerSaveReader#3]
The Save Reader should be aware of being displayed via the desktop app. 
Then there is no point in displaying the hint that there is a desktop app.

**Comment by GingerFitzgerald** [comment]
priority is very low

**Comment by iebb** [comment]
It's planned, but I only added a custom user-agent in version 0.10, and I have no way to detect previous versions, and the website won't know until the savefile click.
