### ISSUE TITLE
Save file serialization fails every time

### ISSUE THREAD

**Issue by Bantam23454** [iebb/F1ManagerSaveReader#5]
Save file serialization fails every time no matter what I do. Happens every time, before it did work fine, so I am unsure what the issue could be.

**Comment by iebb** [comment]
Can you attach your .sav file here? It's pretty weird

**Comment by Bantam23454** [comment]
[autosave.zip](https://github.com/iebb/F1ManagerSaveReader/files/14497544/autosave.zip)

**Comment by iebb** [comment]
should be fixed [here](https://github.com/iebb/F1ManagerSaveReader/commit/ab24e528399a901a9cbd01f3ce131eb170b4bc3d) now. was a bug handling nagative numbers.
